repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
        exclude: |
            (?x)^(
                project/static/common/somedir/|
                project/static/common/aspecificfile.js
            )$
